=== sknlsa20/AllAssignment/Day-8/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3school.org/2001/XMLSchema"  targetNamespace="http://www.student.com" elementFormDefault="qualified">
<xs:element name="students">
<xs:complexType>
  <xs:sequence>
    <xs:element name="student" minOccurs="3" maxOccurs="unbounded">
      <xs:complexType>
         <xs:sequence>
          <xs:element name ="stdid" type="xs:int"/>
          <xs:element name ="stdname" type="xs:string"/>
          <xs:element name ="stdheight" type="xs:double"/>
          <xs:element name ="stdmobile" type="xs:int"/>
         </xs:sequence>
      </xs:complexType>   
    </xs:element>
  </xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== sknlsa20/AllAssignment/Day-8/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:s="http://www.student.com" xmlns:x="http://www.w3school.org/2001/XMLSchema-instance" x:schemaLocation="http://www.student.com student.xsd">
<s:student>
  <s:stdid>679</s:stdid>
  <s:stdname>shiva</s:stdname>
  <s:stdheight>6.7</s:stdheight>
  <s:stdmobile>9898989</s:stdmobile>
</s:student>

<s:student>
  <s:stdid>679</s:stdid>
  <s:stdname>shiva</s:stdname>
  <s:stdheight>6.7</s:stdheight>
  <s:stdmobile>9898989</s:stdmobile>
</s:student>
</students>
